// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "moviepilot-go/internal/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_LoadPlugin_FullMethodName         = "/moviepilot.plugin.PluginService/LoadPlugin"
	PluginService_UnloadPlugin_FullMethodName       = "/moviepilot.plugin.PluginService/UnloadPlugin"
	PluginService_StartPlugin_FullMethodName        = "/moviepilot.plugin.PluginService/StartPlugin"
	PluginService_StopPlugin_FullMethodName         = "/moviepilot.plugin.PluginService/StopPlugin"
	PluginService_GetPluginInfo_FullMethodName      = "/moviepilot.plugin.PluginService/GetPluginInfo"
	PluginService_ListPlugins_FullMethodName        = "/moviepilot.plugin.PluginService/ListPlugins"
	PluginService_ExecutePlugin_FullMethodName      = "/moviepilot.plugin.PluginService/ExecutePlugin"
	PluginService_GetPluginConfig_FullMethodName    = "/moviepilot.plugin.PluginService/GetPluginConfig"
	PluginService_UpdatePluginConfig_FullMethodName = "/moviepilot.plugin.PluginService/UpdatePluginConfig"
	PluginService_HealthCheck_FullMethodName        = "/moviepilot.plugin.PluginService/HealthCheck"
	PluginService_PublishEvent_FullMethodName       = "/moviepilot.plugin.PluginService/PublishEvent"
	PluginService_SubscribeEvent_FullMethodName     = "/moviepilot.plugin.PluginService/SubscribeEvent"
	PluginService_UnsubscribeEvent_FullMethodName   = "/moviepilot.plugin.PluginService/UnsubscribeEvent"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 插件服务定义
type PluginServiceClient interface {
	// 加载插件
	LoadPlugin(ctx context.Context, in *LoadPluginRequest, opts ...grpc.CallOption) (*LoadPluginResponse, error)
	// 卸载插件
	UnloadPlugin(ctx context.Context, in *UnloadPluginRequest, opts ...grpc.CallOption) (*UnloadPluginResponse, error)
	// 启动插件
	StartPlugin(ctx context.Context, in *StartPluginRequest, opts ...grpc.CallOption) (*StartPluginResponse, error)
	// 停止插件
	StopPlugin(ctx context.Context, in *StopPluginRequest, opts ...grpc.CallOption) (*StopPluginResponse, error)
	// 获取插件信息
	GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error)
	// 列出所有插件
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error)
	// 执行插件方法
	ExecutePlugin(ctx context.Context, in *ExecutePluginRequest, opts ...grpc.CallOption) (*ExecutePluginResponse, error)
	// 获取插件配置
	GetPluginConfig(ctx context.Context, in *GetPluginConfigRequest, opts ...grpc.CallOption) (*GetPluginConfigResponse, error)
	// 更新插件配置
	UpdatePluginConfig(ctx context.Context, in *UpdatePluginConfigRequest, opts ...grpc.CallOption) (*UpdatePluginConfigResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *common.HealthCheckRequest, opts ...grpc.CallOption) (*common.HealthCheckResponse, error)
	// 事件相关方法
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
	SubscribeEvent(ctx context.Context, in *SubscribeEventRequest, opts ...grpc.CallOption) (*SubscribeEventResponse, error)
	UnsubscribeEvent(ctx context.Context, in *UnsubscribeEventRequest, opts ...grpc.CallOption) (*UnsubscribeEventResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) LoadPlugin(ctx context.Context, in *LoadPluginRequest, opts ...grpc.CallOption) (*LoadPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadPluginResponse)
	err := c.cc.Invoke(ctx, PluginService_LoadPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UnloadPlugin(ctx context.Context, in *UnloadPluginRequest, opts ...grpc.CallOption) (*UnloadPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadPluginResponse)
	err := c.cc.Invoke(ctx, PluginService_UnloadPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) StartPlugin(ctx context.Context, in *StartPluginRequest, opts ...grpc.CallOption) (*StartPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPluginResponse)
	err := c.cc.Invoke(ctx, PluginService_StartPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) StopPlugin(ctx context.Context, in *StopPluginRequest, opts ...grpc.CallOption) (*StopPluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopPluginResponse)
	err := c.cc.Invoke(ctx, PluginService_StopPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetPluginInfo(ctx context.Context, in *GetPluginInfoRequest, opts ...grpc.CallOption) (*GetPluginInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginInfoResponse)
	err := c.cc.Invoke(ctx, PluginService_GetPluginInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*ListPluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsResponse)
	err := c.cc.Invoke(ctx, PluginService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ExecutePlugin(ctx context.Context, in *ExecutePluginRequest, opts ...grpc.CallOption) (*ExecutePluginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePluginResponse)
	err := c.cc.Invoke(ctx, PluginService_ExecutePlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetPluginConfig(ctx context.Context, in *GetPluginConfigRequest, opts ...grpc.CallOption) (*GetPluginConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPluginConfigResponse)
	err := c.cc.Invoke(ctx, PluginService_GetPluginConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UpdatePluginConfig(ctx context.Context, in *UpdatePluginConfigRequest, opts ...grpc.CallOption) (*UpdatePluginConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePluginConfigResponse)
	err := c.cc.Invoke(ctx, PluginService_UpdatePluginConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HealthCheck(ctx context.Context, in *common.HealthCheckRequest, opts ...grpc.CallOption) (*common.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HealthCheckResponse)
	err := c.cc.Invoke(ctx, PluginService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, PluginService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) SubscribeEvent(ctx context.Context, in *SubscribeEventRequest, opts ...grpc.CallOption) (*SubscribeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeEventResponse)
	err := c.cc.Invoke(ctx, PluginService_SubscribeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UnsubscribeEvent(ctx context.Context, in *UnsubscribeEventRequest, opts ...grpc.CallOption) (*UnsubscribeEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeEventResponse)
	err := c.cc.Invoke(ctx, PluginService_UnsubscribeEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// 插件服务定义
type PluginServiceServer interface {
	// 加载插件
	LoadPlugin(context.Context, *LoadPluginRequest) (*LoadPluginResponse, error)
	// 卸载插件
	UnloadPlugin(context.Context, *UnloadPluginRequest) (*UnloadPluginResponse, error)
	// 启动插件
	StartPlugin(context.Context, *StartPluginRequest) (*StartPluginResponse, error)
	// 停止插件
	StopPlugin(context.Context, *StopPluginRequest) (*StopPluginResponse, error)
	// 获取插件信息
	GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error)
	// 列出所有插件
	ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error)
	// 执行插件方法
	ExecutePlugin(context.Context, *ExecutePluginRequest) (*ExecutePluginResponse, error)
	// 获取插件配置
	GetPluginConfig(context.Context, *GetPluginConfigRequest) (*GetPluginConfigResponse, error)
	// 更新插件配置
	UpdatePluginConfig(context.Context, *UpdatePluginConfigRequest) (*UpdatePluginConfigResponse, error)
	// 健康检查
	HealthCheck(context.Context, *common.HealthCheckRequest) (*common.HealthCheckResponse, error)
	// 事件相关方法
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	SubscribeEvent(context.Context, *SubscribeEventRequest) (*SubscribeEventResponse, error)
	UnsubscribeEvent(context.Context, *UnsubscribeEventRequest) (*UnsubscribeEventResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) LoadPlugin(context.Context, *LoadPluginRequest) (*LoadPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadPlugin not implemented")
}
func (UnimplementedPluginServiceServer) UnloadPlugin(context.Context, *UnloadPluginRequest) (*UnloadPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadPlugin not implemented")
}
func (UnimplementedPluginServiceServer) StartPlugin(context.Context, *StartPluginRequest) (*StartPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPlugin not implemented")
}
func (UnimplementedPluginServiceServer) StopPlugin(context.Context, *StopPluginRequest) (*StopPluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPlugin not implemented")
}
func (UnimplementedPluginServiceServer) GetPluginInfo(context.Context, *GetPluginInfoRequest) (*GetPluginInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginInfo not implemented")
}
func (UnimplementedPluginServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*ListPluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedPluginServiceServer) ExecutePlugin(context.Context, *ExecutePluginRequest) (*ExecutePluginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlugin not implemented")
}
func (UnimplementedPluginServiceServer) GetPluginConfig(context.Context, *GetPluginConfigRequest) (*GetPluginConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPluginConfig not implemented")
}
func (UnimplementedPluginServiceServer) UpdatePluginConfig(context.Context, *UpdatePluginConfigRequest) (*UpdatePluginConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePluginConfig not implemented")
}
func (UnimplementedPluginServiceServer) HealthCheck(context.Context, *common.HealthCheckRequest) (*common.HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedPluginServiceServer) SubscribeEvent(context.Context, *SubscribeEventRequest) (*SubscribeEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeEvent not implemented")
}
func (UnimplementedPluginServiceServer) UnsubscribeEvent(context.Context, *UnsubscribeEventRequest) (*UnsubscribeEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnsubscribeEvent not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_LoadPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).LoadPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_LoadPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).LoadPlugin(ctx, req.(*LoadPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UnloadPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UnloadPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_UnloadPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UnloadPlugin(ctx, req.(*UnloadPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_StartPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).StartPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_StartPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).StartPlugin(ctx, req.(*StartPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_StopPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).StopPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_StopPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).StopPlugin(ctx, req.(*StopPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetPluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetPluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetPluginInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetPluginInfo(ctx, req.(*GetPluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ExecutePlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ExecutePlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ExecutePlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ExecutePlugin(ctx, req.(*ExecutePluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetPluginConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPluginConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetPluginConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetPluginConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetPluginConfig(ctx, req.(*GetPluginConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UpdatePluginConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePluginConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UpdatePluginConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_UpdatePluginConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UpdatePluginConfig(ctx, req.(*UpdatePluginConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HealthCheck(ctx, req.(*common.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_SubscribeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).SubscribeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_SubscribeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).SubscribeEvent(ctx, req.(*SubscribeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UnsubscribeEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UnsubscribeEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_UnsubscribeEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UnsubscribeEvent(ctx, req.(*UnsubscribeEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moviepilot.plugin.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadPlugin",
			Handler:    _PluginService_LoadPlugin_Handler,
		},
		{
			MethodName: "UnloadPlugin",
			Handler:    _PluginService_UnloadPlugin_Handler,
		},
		{
			MethodName: "StartPlugin",
			Handler:    _PluginService_StartPlugin_Handler,
		},
		{
			MethodName: "StopPlugin",
			Handler:    _PluginService_StopPlugin_Handler,
		},
		{
			MethodName: "GetPluginInfo",
			Handler:    _PluginService_GetPluginInfo_Handler,
		},
		{
			MethodName: "ListPlugins",
			Handler:    _PluginService_ListPlugins_Handler,
		},
		{
			MethodName: "ExecutePlugin",
			Handler:    _PluginService_ExecutePlugin_Handler,
		},
		{
			MethodName: "GetPluginConfig",
			Handler:    _PluginService_GetPluginConfig_Handler,
		},
		{
			MethodName: "UpdatePluginConfig",
			Handler:    _PluginService_UpdatePluginConfig_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginService_HealthCheck_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _PluginService_PublishEvent_Handler,
		},
		{
			MethodName: "SubscribeEvent",
			Handler:    _PluginService_SubscribeEvent_Handler,
		},
		{
			MethodName: "UnsubscribeEvent",
			Handler:    _PluginService_UnsubscribeEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
