// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "moviepilot-go/internal/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 插件类型
type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED  PluginType = 0
	PluginType_PLUGIN_TYPE_SITE         PluginType = 1  // 站点插件
	PluginType_PLUGIN_TYPE_INDEXER      PluginType = 2  // 索引器插件
	PluginType_PLUGIN_TYPE_DOWNLOADER   PluginType = 3  // 下载器插件
	PluginType_PLUGIN_TYPE_MEDIASERVER  PluginType = 4  // 媒体服务器插件
	PluginType_PLUGIN_TYPE_NOTIFICATION PluginType = 5  // 通知插件
	PluginType_PLUGIN_TYPE_SCRAPER      PluginType = 6  // 刮削器插件
	PluginType_PLUGIN_TYPE_CUSTOM       PluginType = 99 // 自定义插件
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0:  "PLUGIN_TYPE_UNSPECIFIED",
		1:  "PLUGIN_TYPE_SITE",
		2:  "PLUGIN_TYPE_INDEXER",
		3:  "PLUGIN_TYPE_DOWNLOADER",
		4:  "PLUGIN_TYPE_MEDIASERVER",
		5:  "PLUGIN_TYPE_NOTIFICATION",
		6:  "PLUGIN_TYPE_SCRAPER",
		99: "PLUGIN_TYPE_CUSTOM",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED":  0,
		"PLUGIN_TYPE_SITE":         1,
		"PLUGIN_TYPE_INDEXER":      2,
		"PLUGIN_TYPE_DOWNLOADER":   3,
		"PLUGIN_TYPE_MEDIASERVER":  4,
		"PLUGIN_TYPE_NOTIFICATION": 5,
		"PLUGIN_TYPE_SCRAPER":      6,
		"PLUGIN_TYPE_CUSTOM":       99,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginType.Descriptor instead.
func (PluginType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// 插件状态
type PluginStatus int32

const (
	PluginStatus_PLUGIN_STATUS_UNSPECIFIED PluginStatus = 0
	PluginStatus_PLUGIN_STATUS_LOADED      PluginStatus = 1 // 已加载
	PluginStatus_PLUGIN_STATUS_RUNNING     PluginStatus = 2 // 运行中
	PluginStatus_PLUGIN_STATUS_STOPPED     PluginStatus = 3 // 已停止
	PluginStatus_PLUGIN_STATUS_ERROR       PluginStatus = 4 // 错误
	PluginStatus_PLUGIN_STATUS_DISABLED    PluginStatus = 5 // 已禁用
)

// Enum value maps for PluginStatus.
var (
	PluginStatus_name = map[int32]string{
		0: "PLUGIN_STATUS_UNSPECIFIED",
		1: "PLUGIN_STATUS_LOADED",
		2: "PLUGIN_STATUS_RUNNING",
		3: "PLUGIN_STATUS_STOPPED",
		4: "PLUGIN_STATUS_ERROR",
		5: "PLUGIN_STATUS_DISABLED",
	}
	PluginStatus_value = map[string]int32{
		"PLUGIN_STATUS_UNSPECIFIED": 0,
		"PLUGIN_STATUS_LOADED":      1,
		"PLUGIN_STATUS_RUNNING":     2,
		"PLUGIN_STATUS_STOPPED":     3,
		"PLUGIN_STATUS_ERROR":       4,
		"PLUGIN_STATUS_DISABLED":    5,
	}
)

func (x PluginStatus) Enum() *PluginStatus {
	p := new(PluginStatus)
	*p = x
	return p
}

func (x PluginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[1].Descriptor()
}

func (PluginStatus) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[1]
}

func (x PluginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginStatus.Descriptor instead.
func (PluginStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

type PluginEvent_EventType int32

const (
	PluginEvent_EVENT_TYPE_UNSPECIFIED PluginEvent_EventType = 0
	// 插件生命周期事件
	PluginEvent_EVENT_TYPE_LOADED         PluginEvent_EventType = 1
	PluginEvent_EVENT_TYPE_STARTED        PluginEvent_EventType = 2
	PluginEvent_EVENT_TYPE_STOPPED        PluginEvent_EventType = 3
	PluginEvent_EVENT_TYPE_ERROR          PluginEvent_EventType = 4
	PluginEvent_EVENT_TYPE_CONFIG_CHANGED PluginEvent_EventType = 5
	// 插件命令事件
	PluginEvent_EVENT_TYPE_COMMAND_EXECUTED PluginEvent_EventType = 6
	PluginEvent_EVENT_TYPE_API_EXECUTED     PluginEvent_EventType = 7
	// 系统事件
	PluginEvent_EVENT_TYPE_SYSTEM_STARTED        PluginEvent_EventType = 8
	PluginEvent_EVENT_TYPE_SYSTEM_SHUTDOWN       PluginEvent_EventType = 9
	PluginEvent_EVENT_TYPE_SYSTEM_CONFIG_CHANGED PluginEvent_EventType = 10
	// 媒体相关事件
	PluginEvent_EVENT_TYPE_MEDIA_ADDED      PluginEvent_EventType = 11
	PluginEvent_EVENT_TYPE_MEDIA_UPDATED    PluginEvent_EventType = 12
	PluginEvent_EVENT_TYPE_MEDIA_DELETED    PluginEvent_EventType = 13
	PluginEvent_EVENT_TYPE_MEDIA_DOWNLOADED PluginEvent_EventType = 14
	PluginEvent_EVENT_TYPE_MEDIA_TRANSFERED PluginEvent_EventType = 15
	// 任务相关事件
	PluginEvent_EVENT_TYPE_TASK_CREATED   PluginEvent_EventType = 16
	PluginEvent_EVENT_TYPE_TASK_STARTED   PluginEvent_EventType = 17
	PluginEvent_EVENT_TYPE_TASK_COMPLETED PluginEvent_EventType = 18
	PluginEvent_EVENT_TYPE_TASK_FAILED    PluginEvent_EventType = 19
	PluginEvent_EVENT_TYPE_TASK_CANCELED  PluginEvent_EventType = 20
)

// Enum value maps for PluginEvent_EventType.
var (
	PluginEvent_EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_LOADED",
		2:  "EVENT_TYPE_STARTED",
		3:  "EVENT_TYPE_STOPPED",
		4:  "EVENT_TYPE_ERROR",
		5:  "EVENT_TYPE_CONFIG_CHANGED",
		6:  "EVENT_TYPE_COMMAND_EXECUTED",
		7:  "EVENT_TYPE_API_EXECUTED",
		8:  "EVENT_TYPE_SYSTEM_STARTED",
		9:  "EVENT_TYPE_SYSTEM_SHUTDOWN",
		10: "EVENT_TYPE_SYSTEM_CONFIG_CHANGED",
		11: "EVENT_TYPE_MEDIA_ADDED",
		12: "EVENT_TYPE_MEDIA_UPDATED",
		13: "EVENT_TYPE_MEDIA_DELETED",
		14: "EVENT_TYPE_MEDIA_DOWNLOADED",
		15: "EVENT_TYPE_MEDIA_TRANSFERED",
		16: "EVENT_TYPE_TASK_CREATED",
		17: "EVENT_TYPE_TASK_STARTED",
		18: "EVENT_TYPE_TASK_COMPLETED",
		19: "EVENT_TYPE_TASK_FAILED",
		20: "EVENT_TYPE_TASK_CANCELED",
	}
	PluginEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":           0,
		"EVENT_TYPE_LOADED":                1,
		"EVENT_TYPE_STARTED":               2,
		"EVENT_TYPE_STOPPED":               3,
		"EVENT_TYPE_ERROR":                 4,
		"EVENT_TYPE_CONFIG_CHANGED":        5,
		"EVENT_TYPE_COMMAND_EXECUTED":      6,
		"EVENT_TYPE_API_EXECUTED":          7,
		"EVENT_TYPE_SYSTEM_STARTED":        8,
		"EVENT_TYPE_SYSTEM_SHUTDOWN":       9,
		"EVENT_TYPE_SYSTEM_CONFIG_CHANGED": 10,
		"EVENT_TYPE_MEDIA_ADDED":           11,
		"EVENT_TYPE_MEDIA_UPDATED":         12,
		"EVENT_TYPE_MEDIA_DELETED":         13,
		"EVENT_TYPE_MEDIA_DOWNLOADED":      14,
		"EVENT_TYPE_MEDIA_TRANSFERED":      15,
		"EVENT_TYPE_TASK_CREATED":          16,
		"EVENT_TYPE_TASK_STARTED":          17,
		"EVENT_TYPE_TASK_COMPLETED":        18,
		"EVENT_TYPE_TASK_FAILED":           19,
		"EVENT_TYPE_TASK_CANCELED":         20,
	}
)

func (x PluginEvent_EventType) Enum() *PluginEvent_EventType {
	p := new(PluginEvent_EventType)
	*p = x
	return p
}

func (x PluginEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[2].Descriptor()
}

func (PluginEvent_EventType) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[2]
}

func (x PluginEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginEvent_EventType.Descriptor instead.
func (PluginEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19, 0}
}

// 插件信息
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                        // 插件ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // 插件名称
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                                                                              // 版本号
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`                                                                                // 作者
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                                                                      // 描述
	Type          PluginType             `protobuf:"varint,6,opt,name=type,proto3,enum=moviepilot.plugin.PluginType" json:"type,omitempty"`                                                 // 插件类型
	Status        PluginStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=moviepilot.plugin.PluginStatus" json:"status,omitempty"`                                           // 插件状态
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`                                                                                    // 标签
	Homepage      string                 `protobuf:"bytes,9,opt,name=homepage,proto3" json:"homepage,omitempty"`                                                                            // 主页
	Icon          string                 `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon,omitempty"`                                                                                   // 图标URL
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                       // 创建时间
	UpdatedAt     int64                  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                       // 更新时间
	Metadata      map[string]string      `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func (x *PluginInfo) GetStatus() PluginStatus {
	if x != nil {
		return x.Status
	}
	return PluginStatus_PLUGIN_STATUS_UNSPECIFIED
}

func (x *PluginInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginInfo) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *PluginInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PluginInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PluginInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PluginInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 加载插件请求
type LoadPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`                                                       // 插件ID
	PluginPath    string                 `protobuf:"bytes,2,opt,name=plugin_path,json=pluginPath,proto3" json:"plugin_path,omitempty"`                                                 // 插件路径
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPluginRequest) Reset() {
	*x = LoadPluginRequest{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPluginRequest) ProtoMessage() {}

func (x *LoadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPluginRequest.ProtoReflect.Descriptor instead.
func (*LoadPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *LoadPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *LoadPluginRequest) GetPluginPath() string {
	if x != nil {
		return x.PluginPath
	}
	return ""
}

func (x *LoadPluginRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// 加载插件响应
type LoadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PluginInfo    *PluginInfo            `protobuf:"bytes,2,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPluginResponse) Reset() {
	*x = LoadPluginResponse{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPluginResponse) ProtoMessage() {}

func (x *LoadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPluginResponse.ProtoReflect.Descriptor instead.
func (*LoadPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *LoadPluginResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *LoadPluginResponse) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

// 卸载插件请求
type UnloadPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadPluginRequest) Reset() {
	*x = UnloadPluginRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadPluginRequest) ProtoMessage() {}

func (x *UnloadPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadPluginRequest.ProtoReflect.Descriptor instead.
func (*UnloadPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *UnloadPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// 卸载插件响应
type UnloadPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadPluginResponse) Reset() {
	*x = UnloadPluginResponse{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadPluginResponse) ProtoMessage() {}

func (x *UnloadPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadPluginResponse.ProtoReflect.Descriptor instead.
func (*UnloadPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *UnloadPluginResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// 启动插件请求
type StartPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPluginRequest) Reset() {
	*x = StartPluginRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPluginRequest) ProtoMessage() {}

func (x *StartPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPluginRequest.ProtoReflect.Descriptor instead.
func (*StartPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *StartPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *StartPluginRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// 启动插件响应
type StartPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPluginResponse) Reset() {
	*x = StartPluginResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPluginResponse) ProtoMessage() {}

func (x *StartPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPluginResponse.ProtoReflect.Descriptor instead.
func (*StartPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *StartPluginResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// 停止插件请求
type StopPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // 是否强制停止
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPluginRequest) Reset() {
	*x = StopPluginRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPluginRequest) ProtoMessage() {}

func (x *StopPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPluginRequest.ProtoReflect.Descriptor instead.
func (*StopPluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *StopPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *StopPluginRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// 停止插件响应
type StopPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopPluginResponse) Reset() {
	*x = StopPluginResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopPluginResponse) ProtoMessage() {}

func (x *StopPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopPluginResponse.ProtoReflect.Descriptor instead.
func (*StopPluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *StopPluginResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// 获取插件信息请求
type GetPluginInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoRequest) Reset() {
	*x = GetPluginInfoRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoRequest) ProtoMessage() {}

func (x *GetPluginInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPluginInfoRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *GetPluginInfoRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// 获取插件信息响应
type GetPluginInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PluginInfo    *PluginInfo            `protobuf:"bytes,2,opt,name=plugin_info,json=pluginInfo,proto3" json:"plugin_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginInfoResponse) Reset() {
	*x = GetPluginInfoResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginInfoResponse) ProtoMessage() {}

func (x *GetPluginInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPluginInfoResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *GetPluginInfoResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetPluginInfoResponse) GetPluginInfo() *PluginInfo {
	if x != nil {
		return x.PluginInfo
	}
	return nil
}

// 列出插件请求
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PluginType             `protobuf:"varint,1,opt,name=type,proto3,enum=moviepilot.plugin.PluginType" json:"type,omitempty"`       // 插件类型过滤
	Status        PluginStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=moviepilot.plugin.PluginStatus" json:"status,omitempty"` // 状态过滤
	Page          *common.PageRequest    `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`                                          // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ListPluginsRequest) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func (x *ListPluginsRequest) GetStatus() PluginStatus {
	if x != nil {
		return x.Status
	}
	return PluginStatus_PLUGIN_STATUS_UNSPECIFIED
}

func (x *ListPluginsRequest) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// 列出插件响应
type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Plugins       []*PluginInfo          `protobuf:"bytes,2,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Page          *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ListPluginsResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *ListPluginsResponse) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// 执行插件请求
type ExecutePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`    // 方法名
	Params        []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`    // 参数（JSON序列化）
	Timeout       int32                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"` // 超时时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePluginRequest) Reset() {
	*x = ExecutePluginRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePluginRequest) ProtoMessage() {}

func (x *ExecutePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePluginRequest.ProtoReflect.Descriptor instead.
func (*ExecutePluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ExecutePluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ExecutePluginRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ExecutePluginRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecutePluginRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 执行插件响应
type ExecutePluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                                     // 结果（JSON序列化）
	ExecutionTime int64                  `protobuf:"varint,3,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"` // 执行时间（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePluginResponse) Reset() {
	*x = ExecutePluginResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePluginResponse) ProtoMessage() {}

func (x *ExecutePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePluginResponse.ProtoReflect.Descriptor instead.
func (*ExecutePluginResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutePluginResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ExecutePluginResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutePluginResponse) GetExecutionTime() int64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

// 获取插件配置请求
type GetPluginConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginConfigRequest) Reset() {
	*x = GetPluginConfigRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfigRequest) ProtoMessage() {}

func (x *GetPluginConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPluginConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *GetPluginConfigRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// 获取插件配置响应
type GetPluginConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Config        []*common.ConfigItem   `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPluginConfigResponse) Reset() {
	*x = GetPluginConfigResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPluginConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfigResponse) ProtoMessage() {}

func (x *GetPluginConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPluginConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *GetPluginConfigResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetPluginConfigResponse) GetConfig() []*common.ConfigItem {
	if x != nil {
		return x.Config
	}
	return nil
}

// 更新插件配置请求
type UpdatePluginConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Config        []*common.ConfigItem   `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginConfigRequest) Reset() {
	*x = UpdatePluginConfigRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginConfigRequest) ProtoMessage() {}

func (x *UpdatePluginConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdatePluginConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePluginConfigRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *UpdatePluginConfigRequest) GetConfig() []*common.ConfigItem {
	if x != nil {
		return x.Config
	}
	return nil
}

// 更新插件配置响应
type UpdatePluginConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginConfigResponse) Reset() {
	*x = UpdatePluginConfigResponse{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginConfigResponse) ProtoMessage() {}

func (x *UpdatePluginConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdatePluginConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *UpdatePluginConfigResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// 插件事件
type PluginEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PluginEvent_EventType  `protobuf:"varint,1,opt,name=type,proto3,enum=moviepilot.plugin.PluginEvent_EventType" json:"type,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string][]byte      `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEvent) Reset() {
	*x = PluginEvent{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEvent) ProtoMessage() {}

func (x *PluginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEvent.ProtoReflect.Descriptor instead.
func (*PluginEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *PluginEvent) GetType() PluginEvent_EventType {
	if x != nil {
		return x.Type
	}
	return PluginEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *PluginEvent) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PluginEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PluginEvent) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 发布事件请求
type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Data          map[string][]byte      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *PublishEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PublishEventRequest) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PublishEventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 发布事件响应
type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *PublishEventResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// 订阅事件请求
type SubscribeEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PluginId      string                 `protobuf:"bytes,2,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventRequest) Reset() {
	*x = SubscribeEventRequest{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventRequest) ProtoMessage() {}

func (x *SubscribeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *SubscribeEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SubscribeEventRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// 订阅事件响应
type SubscribeEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeEventResponse) Reset() {
	*x = SubscribeEventResponse{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventResponse) ProtoMessage() {}

func (x *SubscribeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventResponse.ProtoReflect.Descriptor instead.
func (*SubscribeEventResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *SubscribeEventResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SubscribeEventResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// 取消订阅事件请求
type UnsubscribeEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsubscribeEventRequest) Reset() {
	*x = UnsubscribeEventRequest{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeEventRequest) ProtoMessage() {}

func (x *UnsubscribeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeEventRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeEventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *UnsubscribeEventRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

// 取消订阅事件响应
type UnsubscribeEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *common.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeEventResponse) Reset() {
	*x = UnsubscribeEventResponse{}
	mi := &file_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeEventResponse) ProtoMessage() {}

func (x *UnsubscribeEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeEventResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeEventResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *UnsubscribeEventResponse) GetStatus() *common.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x11moviepilot.plugin\x1a\fcommon.proto\"\xf8\x03\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x121\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1d.moviepilot.plugin.PluginTypeR\x04type\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.moviepilot.plugin.PluginStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1a\n" +
	"\bhomepage\x18\t \x01(\tR\bhomepage\x12\x12\n" +
	"\x04icon\x18\n" +
	" \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03R\tupdatedAt\x12G\n" +
	"\bmetadata\x18\r \x03(\v2+.moviepilot.plugin.PluginInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x11LoadPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vplugin_path\x18\x02 \x01(\tR\n" +
	"pluginPath\x12H\n" +
	"\x06config\x18\x03 \x03(\v20.moviepilot.plugin.LoadPluginRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\x12LoadPluginResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\x12>\n" +
	"\vplugin_info\x18\x02 \x01(\v2\x1d.moviepilot.plugin.PluginInfoR\n" +
	"pluginInfo\"2\n" +
	"\x13UnloadPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"I\n" +
	"\x14UnloadPluginResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\"\xb7\x01\n" +
	"\x12StartPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12I\n" +
	"\x06params\x18\x02 \x03(\v21.moviepilot.plugin.StartPluginRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x13StartPluginResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\"F\n" +
	"\x11StopPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"G\n" +
	"\x12StopPluginResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\"3\n" +
	"\x14GetPluginInfoRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"\x8a\x01\n" +
	"\x15GetPluginInfoResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\x12>\n" +
	"\vplugin_info\x18\x02 \x01(\v2\x1d.moviepilot.plugin.PluginInfoR\n" +
	"pluginInfo\"\xb4\x01\n" +
	"\x12ListPluginsRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.moviepilot.plugin.PluginTypeR\x04type\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.moviepilot.plugin.PluginStatusR\x06status\x122\n" +
	"\x04page\x18\x03 \x01(\v2\x1e.moviepilot.common.PageRequestR\x04page\"\xb6\x01\n" +
	"\x13ListPluginsResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\x127\n" +
	"\aplugins\x18\x02 \x03(\v2\x1d.moviepilot.plugin.PluginInfoR\aplugins\x123\n" +
	"\x04page\x18\x03 \x01(\v2\x1f.moviepilot.common.PageResponseR\x04page\"}\n" +
	"\x14ExecutePluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x05R\atimeout\"\x89\x01\n" +
	"\x15ExecutePluginResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12%\n" +
	"\x0eexecution_time\x18\x03 \x01(\x03R\rexecutionTime\"5\n" +
	"\x16GetPluginConfigRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"\x83\x01\n" +
	"\x17GetPluginConfigResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\x125\n" +
	"\x06config\x18\x02 \x03(\v2\x1d.moviepilot.common.ConfigItemR\x06config\"o\n" +
	"\x19UpdatePluginConfigRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x125\n" +
	"\x06config\x18\x02 \x03(\v2\x1d.moviepilot.common.ConfigItemR\x06config\"O\n" +
	"\x1aUpdatePluginConfigResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\"\xa5\a\n" +
	"\vPluginEvent\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.moviepilot.plugin.PluginEvent.EventTypeR\x04type\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12<\n" +
	"\x04data\x18\x06 \x03(\v2(.moviepilot.plugin.PluginEvent.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xf3\x04\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EVENT_TYPE_LOADED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_STARTED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_STOPPED\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_CONFIG_CHANGED\x10\x05\x12\x1f\n" +
	"\x1bEVENT_TYPE_COMMAND_EXECUTED\x10\x06\x12\x1b\n" +
	"\x17EVENT_TYPE_API_EXECUTED\x10\a\x12\x1d\n" +
	"\x19EVENT_TYPE_SYSTEM_STARTED\x10\b\x12\x1e\n" +
	"\x1aEVENT_TYPE_SYSTEM_SHUTDOWN\x10\t\x12$\n" +
	" EVENT_TYPE_SYSTEM_CONFIG_CHANGED\x10\n" +
	"\x12\x1a\n" +
	"\x16EVENT_TYPE_MEDIA_ADDED\x10\v\x12\x1c\n" +
	"\x18EVENT_TYPE_MEDIA_UPDATED\x10\f\x12\x1c\n" +
	"\x18EVENT_TYPE_MEDIA_DELETED\x10\r\x12\x1f\n" +
	"\x1bEVENT_TYPE_MEDIA_DOWNLOADED\x10\x0e\x12\x1f\n" +
	"\x1bEVENT_TYPE_MEDIA_TRANSFERED\x10\x0f\x12\x1b\n" +
	"\x17EVENT_TYPE_TASK_CREATED\x10\x10\x12\x1b\n" +
	"\x17EVENT_TYPE_TASK_STARTED\x10\x11\x12\x1d\n" +
	"\x19EVENT_TYPE_TASK_COMPLETED\x10\x12\x12\x1a\n" +
	"\x16EVENT_TYPE_TASK_FAILED\x10\x13\x12\x1c\n" +
	"\x18EVENT_TYPE_TASK_CANCELED\x10\x14\"\x84\x02\n" +
	"\x13PublishEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12D\n" +
	"\x04data\x18\x04 \x03(\v20.moviepilot.plugin.PublishEventRequest.DataEntryR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"I\n" +
	"\x14PublishEventResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\"S\n" +
	"\x15SubscribeEventRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tplugin_id\x18\x02 \x01(\tR\bpluginId\"t\n" +
	"\x16SubscribeEventResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\"B\n" +
	"\x17UnsubscribeEventRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"M\n" +
	"\x18UnsubscribeEventResponse\x121\n" +
	"\x06status\x18\x01 \x01(\v2\x19.moviepilot.common.StatusR\x06status*\xe0\x01\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PLUGIN_TYPE_SITE\x10\x01\x12\x17\n" +
	"\x13PLUGIN_TYPE_INDEXER\x10\x02\x12\x1a\n" +
	"\x16PLUGIN_TYPE_DOWNLOADER\x10\x03\x12\x1b\n" +
	"\x17PLUGIN_TYPE_MEDIASERVER\x10\x04\x12\x1c\n" +
	"\x18PLUGIN_TYPE_NOTIFICATION\x10\x05\x12\x17\n" +
	"\x13PLUGIN_TYPE_SCRAPER\x10\x06\x12\x16\n" +
	"\x12PLUGIN_TYPE_CUSTOM\x10c*\xb2\x01\n" +
	"\fPluginStatus\x12\x1d\n" +
	"\x19PLUGIN_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PLUGIN_STATUS_LOADED\x10\x01\x12\x19\n" +
	"\x15PLUGIN_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15PLUGIN_STATUS_STOPPED\x10\x03\x12\x17\n" +
	"\x13PLUGIN_STATUS_ERROR\x10\x04\x12\x1a\n" +
	"\x16PLUGIN_STATUS_DISABLED\x10\x052\x9a\n" +
	"\n" +
	"\rPluginService\x12Y\n" +
	"\n" +
	"LoadPlugin\x12$.moviepilot.plugin.LoadPluginRequest\x1a%.moviepilot.plugin.LoadPluginResponse\x12_\n" +
	"\fUnloadPlugin\x12&.moviepilot.plugin.UnloadPluginRequest\x1a'.moviepilot.plugin.UnloadPluginResponse\x12\\\n" +
	"\vStartPlugin\x12%.moviepilot.plugin.StartPluginRequest\x1a&.moviepilot.plugin.StartPluginResponse\x12Y\n" +
	"\n" +
	"StopPlugin\x12$.moviepilot.plugin.StopPluginRequest\x1a%.moviepilot.plugin.StopPluginResponse\x12b\n" +
	"\rGetPluginInfo\x12'.moviepilot.plugin.GetPluginInfoRequest\x1a(.moviepilot.plugin.GetPluginInfoResponse\x12\\\n" +
	"\vListPlugins\x12%.moviepilot.plugin.ListPluginsRequest\x1a&.moviepilot.plugin.ListPluginsResponse\x12b\n" +
	"\rExecutePlugin\x12'.moviepilot.plugin.ExecutePluginRequest\x1a(.moviepilot.plugin.ExecutePluginResponse\x12h\n" +
	"\x0fGetPluginConfig\x12).moviepilot.plugin.GetPluginConfigRequest\x1a*.moviepilot.plugin.GetPluginConfigResponse\x12q\n" +
	"\x12UpdatePluginConfig\x12,.moviepilot.plugin.UpdatePluginConfigRequest\x1a-.moviepilot.plugin.UpdatePluginConfigResponse\x12\\\n" +
	"\vHealthCheck\x12%.moviepilot.common.HealthCheckRequest\x1a&.moviepilot.common.HealthCheckResponse\x12_\n" +
	"\fPublishEvent\x12&.moviepilot.plugin.PublishEventRequest\x1a'.moviepilot.plugin.PublishEventResponse\x12e\n" +
	"\x0eSubscribeEvent\x12(.moviepilot.plugin.SubscribeEventRequest\x1a).moviepilot.plugin.SubscribeEventResponse\x12k\n" +
	"\x10UnsubscribeEvent\x12*.moviepilot.plugin.UnsubscribeEventRequest\x1a+.moviepilot.plugin.UnsubscribeEventResponseB%Z#moviepilot-go/internal/proto/pluginb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_plugin_proto_goTypes = []any{
	(PluginType)(0),                    // 0: moviepilot.plugin.PluginType
	(PluginStatus)(0),                  // 1: moviepilot.plugin.PluginStatus
	(PluginEvent_EventType)(0),         // 2: moviepilot.plugin.PluginEvent.EventType
	(*PluginInfo)(nil),                 // 3: moviepilot.plugin.PluginInfo
	(*LoadPluginRequest)(nil),          // 4: moviepilot.plugin.LoadPluginRequest
	(*LoadPluginResponse)(nil),         // 5: moviepilot.plugin.LoadPluginResponse
	(*UnloadPluginRequest)(nil),        // 6: moviepilot.plugin.UnloadPluginRequest
	(*UnloadPluginResponse)(nil),       // 7: moviepilot.plugin.UnloadPluginResponse
	(*StartPluginRequest)(nil),         // 8: moviepilot.plugin.StartPluginRequest
	(*StartPluginResponse)(nil),        // 9: moviepilot.plugin.StartPluginResponse
	(*StopPluginRequest)(nil),          // 10: moviepilot.plugin.StopPluginRequest
	(*StopPluginResponse)(nil),         // 11: moviepilot.plugin.StopPluginResponse
	(*GetPluginInfoRequest)(nil),       // 12: moviepilot.plugin.GetPluginInfoRequest
	(*GetPluginInfoResponse)(nil),      // 13: moviepilot.plugin.GetPluginInfoResponse
	(*ListPluginsRequest)(nil),         // 14: moviepilot.plugin.ListPluginsRequest
	(*ListPluginsResponse)(nil),        // 15: moviepilot.plugin.ListPluginsResponse
	(*ExecutePluginRequest)(nil),       // 16: moviepilot.plugin.ExecutePluginRequest
	(*ExecutePluginResponse)(nil),      // 17: moviepilot.plugin.ExecutePluginResponse
	(*GetPluginConfigRequest)(nil),     // 18: moviepilot.plugin.GetPluginConfigRequest
	(*GetPluginConfigResponse)(nil),    // 19: moviepilot.plugin.GetPluginConfigResponse
	(*UpdatePluginConfigRequest)(nil),  // 20: moviepilot.plugin.UpdatePluginConfigRequest
	(*UpdatePluginConfigResponse)(nil), // 21: moviepilot.plugin.UpdatePluginConfigResponse
	(*PluginEvent)(nil),                // 22: moviepilot.plugin.PluginEvent
	(*PublishEventRequest)(nil),        // 23: moviepilot.plugin.PublishEventRequest
	(*PublishEventResponse)(nil),       // 24: moviepilot.plugin.PublishEventResponse
	(*SubscribeEventRequest)(nil),      // 25: moviepilot.plugin.SubscribeEventRequest
	(*SubscribeEventResponse)(nil),     // 26: moviepilot.plugin.SubscribeEventResponse
	(*UnsubscribeEventRequest)(nil),    // 27: moviepilot.plugin.UnsubscribeEventRequest
	(*UnsubscribeEventResponse)(nil),   // 28: moviepilot.plugin.UnsubscribeEventResponse
	nil,                                // 29: moviepilot.plugin.PluginInfo.MetadataEntry
	nil,                                // 30: moviepilot.plugin.LoadPluginRequest.ConfigEntry
	nil,                                // 31: moviepilot.plugin.StartPluginRequest.ParamsEntry
	nil,                                // 32: moviepilot.plugin.PluginEvent.DataEntry
	nil,                                // 33: moviepilot.plugin.PublishEventRequest.DataEntry
	(*common.Status)(nil),              // 34: moviepilot.common.Status
	(*common.PageRequest)(nil),         // 35: moviepilot.common.PageRequest
	(*common.PageResponse)(nil),        // 36: moviepilot.common.PageResponse
	(*common.ConfigItem)(nil),          // 37: moviepilot.common.ConfigItem
	(*common.HealthCheckRequest)(nil),  // 38: moviepilot.common.HealthCheckRequest
	(*common.HealthCheckResponse)(nil), // 39: moviepilot.common.HealthCheckResponse
}
var file_plugin_proto_depIdxs = []int32{
	0,  // 0: moviepilot.plugin.PluginInfo.type:type_name -> moviepilot.plugin.PluginType
	1,  // 1: moviepilot.plugin.PluginInfo.status:type_name -> moviepilot.plugin.PluginStatus
	29, // 2: moviepilot.plugin.PluginInfo.metadata:type_name -> moviepilot.plugin.PluginInfo.MetadataEntry
	30, // 3: moviepilot.plugin.LoadPluginRequest.config:type_name -> moviepilot.plugin.LoadPluginRequest.ConfigEntry
	34, // 4: moviepilot.plugin.LoadPluginResponse.status:type_name -> moviepilot.common.Status
	3,  // 5: moviepilot.plugin.LoadPluginResponse.plugin_info:type_name -> moviepilot.plugin.PluginInfo
	34, // 6: moviepilot.plugin.UnloadPluginResponse.status:type_name -> moviepilot.common.Status
	31, // 7: moviepilot.plugin.StartPluginRequest.params:type_name -> moviepilot.plugin.StartPluginRequest.ParamsEntry
	34, // 8: moviepilot.plugin.StartPluginResponse.status:type_name -> moviepilot.common.Status
	34, // 9: moviepilot.plugin.StopPluginResponse.status:type_name -> moviepilot.common.Status
	34, // 10: moviepilot.plugin.GetPluginInfoResponse.status:type_name -> moviepilot.common.Status
	3,  // 11: moviepilot.plugin.GetPluginInfoResponse.plugin_info:type_name -> moviepilot.plugin.PluginInfo
	0,  // 12: moviepilot.plugin.ListPluginsRequest.type:type_name -> moviepilot.plugin.PluginType
	1,  // 13: moviepilot.plugin.ListPluginsRequest.status:type_name -> moviepilot.plugin.PluginStatus
	35, // 14: moviepilot.plugin.ListPluginsRequest.page:type_name -> moviepilot.common.PageRequest
	34, // 15: moviepilot.plugin.ListPluginsResponse.status:type_name -> moviepilot.common.Status
	3,  // 16: moviepilot.plugin.ListPluginsResponse.plugins:type_name -> moviepilot.plugin.PluginInfo
	36, // 17: moviepilot.plugin.ListPluginsResponse.page:type_name -> moviepilot.common.PageResponse
	34, // 18: moviepilot.plugin.ExecutePluginResponse.status:type_name -> moviepilot.common.Status
	34, // 19: moviepilot.plugin.GetPluginConfigResponse.status:type_name -> moviepilot.common.Status
	37, // 20: moviepilot.plugin.GetPluginConfigResponse.config:type_name -> moviepilot.common.ConfigItem
	37, // 21: moviepilot.plugin.UpdatePluginConfigRequest.config:type_name -> moviepilot.common.ConfigItem
	34, // 22: moviepilot.plugin.UpdatePluginConfigResponse.status:type_name -> moviepilot.common.Status
	2,  // 23: moviepilot.plugin.PluginEvent.type:type_name -> moviepilot.plugin.PluginEvent.EventType
	32, // 24: moviepilot.plugin.PluginEvent.data:type_name -> moviepilot.plugin.PluginEvent.DataEntry
	33, // 25: moviepilot.plugin.PublishEventRequest.data:type_name -> moviepilot.plugin.PublishEventRequest.DataEntry
	34, // 26: moviepilot.plugin.PublishEventResponse.status:type_name -> moviepilot.common.Status
	34, // 27: moviepilot.plugin.SubscribeEventResponse.status:type_name -> moviepilot.common.Status
	34, // 28: moviepilot.plugin.UnsubscribeEventResponse.status:type_name -> moviepilot.common.Status
	4,  // 29: moviepilot.plugin.PluginService.LoadPlugin:input_type -> moviepilot.plugin.LoadPluginRequest
	6,  // 30: moviepilot.plugin.PluginService.UnloadPlugin:input_type -> moviepilot.plugin.UnloadPluginRequest
	8,  // 31: moviepilot.plugin.PluginService.StartPlugin:input_type -> moviepilot.plugin.StartPluginRequest
	10, // 32: moviepilot.plugin.PluginService.StopPlugin:input_type -> moviepilot.plugin.StopPluginRequest
	12, // 33: moviepilot.plugin.PluginService.GetPluginInfo:input_type -> moviepilot.plugin.GetPluginInfoRequest
	14, // 34: moviepilot.plugin.PluginService.ListPlugins:input_type -> moviepilot.plugin.ListPluginsRequest
	16, // 35: moviepilot.plugin.PluginService.ExecutePlugin:input_type -> moviepilot.plugin.ExecutePluginRequest
	18, // 36: moviepilot.plugin.PluginService.GetPluginConfig:input_type -> moviepilot.plugin.GetPluginConfigRequest
	20, // 37: moviepilot.plugin.PluginService.UpdatePluginConfig:input_type -> moviepilot.plugin.UpdatePluginConfigRequest
	38, // 38: moviepilot.plugin.PluginService.HealthCheck:input_type -> moviepilot.common.HealthCheckRequest
	23, // 39: moviepilot.plugin.PluginService.PublishEvent:input_type -> moviepilot.plugin.PublishEventRequest
	25, // 40: moviepilot.plugin.PluginService.SubscribeEvent:input_type -> moviepilot.plugin.SubscribeEventRequest
	27, // 41: moviepilot.plugin.PluginService.UnsubscribeEvent:input_type -> moviepilot.plugin.UnsubscribeEventRequest
	5,  // 42: moviepilot.plugin.PluginService.LoadPlugin:output_type -> moviepilot.plugin.LoadPluginResponse
	7,  // 43: moviepilot.plugin.PluginService.UnloadPlugin:output_type -> moviepilot.plugin.UnloadPluginResponse
	9,  // 44: moviepilot.plugin.PluginService.StartPlugin:output_type -> moviepilot.plugin.StartPluginResponse
	11, // 45: moviepilot.plugin.PluginService.StopPlugin:output_type -> moviepilot.plugin.StopPluginResponse
	13, // 46: moviepilot.plugin.PluginService.GetPluginInfo:output_type -> moviepilot.plugin.GetPluginInfoResponse
	15, // 47: moviepilot.plugin.PluginService.ListPlugins:output_type -> moviepilot.plugin.ListPluginsResponse
	17, // 48: moviepilot.plugin.PluginService.ExecutePlugin:output_type -> moviepilot.plugin.ExecutePluginResponse
	19, // 49: moviepilot.plugin.PluginService.GetPluginConfig:output_type -> moviepilot.plugin.GetPluginConfigResponse
	21, // 50: moviepilot.plugin.PluginService.UpdatePluginConfig:output_type -> moviepilot.plugin.UpdatePluginConfigResponse
	39, // 51: moviepilot.plugin.PluginService.HealthCheck:output_type -> moviepilot.common.HealthCheckResponse
	24, // 52: moviepilot.plugin.PluginService.PublishEvent:output_type -> moviepilot.plugin.PublishEventResponse
	26, // 53: moviepilot.plugin.PluginService.SubscribeEvent:output_type -> moviepilot.plugin.SubscribeEventResponse
	28, // 54: moviepilot.plugin.PluginService.UnsubscribeEvent:output_type -> moviepilot.plugin.UnsubscribeEventResponse
	42, // [42:55] is the sub-list for method output_type
	29, // [29:42] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
