// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: plugin_media.proto

package plugin_media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 站点搜索 ==========
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Sites         []string               `protobuf:"bytes,2,rep,name=sites,proto3" json:"sites,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // movie, tv
	Season        int32                  `protobuf:"varint,4,opt,name=season,proto3" json:"season,omitempty"`
	Episode       int32                  `protobuf:"varint,5,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_plugin_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchRequest) GetSites() []string {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *SearchRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *SearchRequest) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *SearchRequest) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*TorrentInfo         `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_plugin_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetTorrents() []*TorrentInfo {
	if x != nil {
		return x.Torrents
	}
	return nil
}

func (x *SearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TorrentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Site          string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	PageUrl       string                 `protobuf:"bytes,4,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Seeders       int32                  `protobuf:"varint,6,opt,name=seeders,proto3" json:"seeders,omitempty"`
	Leechers      int32                  `protobuf:"varint,7,opt,name=leechers,proto3" json:"leechers,omitempty"`
	PublishDate   string                 `protobuf:"bytes,8,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentInfo) Reset() {
	*x = TorrentInfo{}
	mi := &file_plugin_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentInfo) ProtoMessage() {}

func (x *TorrentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentInfo.ProtoReflect.Descriptor instead.
func (*TorrentInfo) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{2}
}

func (x *TorrentInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TorrentInfo) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *TorrentInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *TorrentInfo) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *TorrentInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TorrentInfo) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *TorrentInfo) GetLeechers() int32 {
	if x != nil {
		return x.Leechers
	}
	return 0
}

func (x *TorrentInfo) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

func (x *TorrentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TorrentInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ========== TMDB 识别 ==========
type RecognizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	MediaType     string                 `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"` // movie, tv
	TmdbId        int32                  `protobuf:"varint,4,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_plugin_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{3}
}

func (x *RecognizeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecognizeRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RecognizeRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *RecognizeRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

type RecognizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_plugin_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{4}
}

func (x *RecognizeResponse) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *RecognizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmdbId        int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle string                 `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	MediaType     string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Overview      string                 `protobuf:"bytes,6,opt,name=overview,proto3" json:"overview,omitempty"`
	PosterPath    string                 `protobuf:"bytes,7,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath  string                 `protobuf:"bytes,8,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	VoteAverage   float64                `protobuf:"fixed64,9,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	Genres        []string               `protobuf:"bytes,10,rep,name=genres,proto3" json:"genres,omitempty"`
	// TV 专用
	SeasonCount   int32 `protobuf:"varint,11,opt,name=season_count,json=seasonCount,proto3" json:"season_count,omitempty"`
	EpisodeCount  int32 `protobuf:"varint,12,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_plugin_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{5}
}

func (x *MediaInfo) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *MediaInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MediaInfo) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *MediaInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *MediaInfo) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *MediaInfo) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *MediaInfo) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *MediaInfo) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *MediaInfo) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

func (x *MediaInfo) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *MediaInfo) GetSeasonCount() int32 {
	if x != nil {
		return x.SeasonCount
	}
	return 0
}

func (x *MediaInfo) GetEpisodeCount() int32 {
	if x != nil {
		return x.EpisodeCount
	}
	return 0
}

// ========== 存储操作 ==========
type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageType   string                 `protobuf:"bytes,1,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"` // local, alist, alipan, u115, smb, rclone
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_plugin_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_plugin_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilesResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModifiedTime  string                 `protobuf:"bytes,5,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_plugin_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{8}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetModifiedTime() string {
	if x != nil {
		return x.ModifiedTime
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageType   string                 `protobuf:"bytes,1,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	LocalPath     string                 `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath    string                 `protobuf:"bytes,3,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_plugin_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{9}
}

func (x *UploadFileRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *UploadFileRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadFileRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_plugin_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageType   string                 `protobuf:"bytes,1,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	LocalPath     string                 `protobuf:"bytes,3,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_plugin_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadFileRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *DownloadFileRequest) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *DownloadFileRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_plugin_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DownloadFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ========== 健康检查 ==========
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_plugin_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{13}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_plugin_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_media_proto_rawDescGZIP(), []int{14}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_plugin_media_proto protoreflect.FileDescriptor

const file_plugin_media_proto_rawDesc = "" +
	"\n" +
	"\x12plugin_media.proto\x12\x17moviepilot.plugin.media\"\x90\x01\n" +
	"\rSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05sites\x18\x02 \x03(\tR\x05sites\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06season\x18\x04 \x01(\x05R\x06season\x12\x18\n" +
	"\aepisode\x18\x05 \x01(\x05R\aepisode\"h\n" +
	"\x0eSearchResponse\x12@\n" +
	"\btorrents\x18\x01 \x03(\v2$.moviepilot.plugin.media.TorrentInfoR\btorrents\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x98\x02\n" +
	"\vTorrentInfo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x19\n" +
	"\bpage_url\x18\x04 \x01(\tR\apageUrl\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x18\n" +
	"\aseeders\x18\x06 \x01(\x05R\aseeders\x12\x1a\n" +
	"\bleechers\x18\a \x01(\x05R\bleechers\x12!\n" +
	"\fpublish_date\x18\b \x01(\tR\vpublishDate\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\"r\n" +
	"\x10RecognizeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x17\n" +
	"\atmdb_id\x18\x04 \x01(\x05R\x06tmdbId\"c\n" +
	"\x11RecognizeResponse\x128\n" +
	"\x05media\x18\x01 \x01(\v2\".moviepilot.plugin.media.MediaInfoR\x05media\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf9\x02\n" +
	"\tMediaInfo\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tR\roriginalTitle\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x12\x1a\n" +
	"\boverview\x18\x06 \x01(\tR\boverview\x12\x1f\n" +
	"\vposter_path\x18\a \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\b \x01(\tR\fbackdropPath\x12!\n" +
	"\fvote_average\x18\t \x01(\x01R\vvoteAverage\x12\x16\n" +
	"\x06genres\x18\n" +
	" \x03(\tR\x06genres\x12!\n" +
	"\fseason_count\x18\v \x01(\x05R\vseasonCount\x12#\n" +
	"\repisode_count\x18\f \x01(\x05R\fepisodeCount\"I\n" +
	"\x10ListFilesRequest\x12!\n" +
	"\fstorage_type\x18\x01 \x01(\tR\vstorageType\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"b\n" +
	"\x11ListFilesResponse\x127\n" +
	"\x05files\x18\x01 \x03(\v2!.moviepilot.plugin.media.FileInfoR\x05files\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x82\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12#\n" +
	"\rmodified_time\x18\x05 \x01(\tR\fmodifiedTime\"v\n" +
	"\x11UploadFileRequest\x12!\n" +
	"\fstorage_type\x18\x01 \x01(\tR\vstorageType\x12\x1d\n" +
	"\n" +
	"local_path\x18\x02 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x03 \x01(\tR\n" +
	"remotePath\"D\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"x\n" +
	"\x13DownloadFileRequest\x12!\n" +
	"\fstorage_type\x18\x01 \x01(\tR\vstorageType\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"local_path\x18\x03 \x01(\tR\tlocalPath\"F\n" +
	"\x14DownloadFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x82\x05\n" +
	"\x12PluginMediaService\x12a\n" +
	"\x0eSearchTorrents\x12&.moviepilot.plugin.media.SearchRequest\x1a'.moviepilot.plugin.media.SearchResponse\x12g\n" +
	"\x0eRecognizeMedia\x12).moviepilot.plugin.media.RecognizeRequest\x1a*.moviepilot.plugin.media.RecognizeResponse\x12b\n" +
	"\tListFiles\x12).moviepilot.plugin.media.ListFilesRequest\x1a*.moviepilot.plugin.media.ListFilesResponse\x12e\n" +
	"\n" +
	"UploadFile\x12*.moviepilot.plugin.media.UploadFileRequest\x1a+.moviepilot.plugin.media.UploadFileResponse\x12k\n" +
	"\fDownloadFile\x12,.moviepilot.plugin.media.DownloadFileRequest\x1a-.moviepilot.plugin.media.DownloadFileResponse\x12h\n" +
	"\vHealthCheck\x12+.moviepilot.plugin.media.HealthCheckRequest\x1a,.moviepilot.plugin.media.HealthCheckResponseB+Z)moviepilot-go/internal/proto/plugin_mediab\x06proto3"

var (
	file_plugin_media_proto_rawDescOnce sync.Once
	file_plugin_media_proto_rawDescData []byte
)

func file_plugin_media_proto_rawDescGZIP() []byte {
	file_plugin_media_proto_rawDescOnce.Do(func() {
		file_plugin_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_media_proto_rawDesc), len(file_plugin_media_proto_rawDesc)))
	})
	return file_plugin_media_proto_rawDescData
}

var file_plugin_media_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_plugin_media_proto_goTypes = []any{
	(*SearchRequest)(nil),        // 0: moviepilot.plugin.media.SearchRequest
	(*SearchResponse)(nil),       // 1: moviepilot.plugin.media.SearchResponse
	(*TorrentInfo)(nil),          // 2: moviepilot.plugin.media.TorrentInfo
	(*RecognizeRequest)(nil),     // 3: moviepilot.plugin.media.RecognizeRequest
	(*RecognizeResponse)(nil),    // 4: moviepilot.plugin.media.RecognizeResponse
	(*MediaInfo)(nil),            // 5: moviepilot.plugin.media.MediaInfo
	(*ListFilesRequest)(nil),     // 6: moviepilot.plugin.media.ListFilesRequest
	(*ListFilesResponse)(nil),    // 7: moviepilot.plugin.media.ListFilesResponse
	(*FileInfo)(nil),             // 8: moviepilot.plugin.media.FileInfo
	(*UploadFileRequest)(nil),    // 9: moviepilot.plugin.media.UploadFileRequest
	(*UploadFileResponse)(nil),   // 10: moviepilot.plugin.media.UploadFileResponse
	(*DownloadFileRequest)(nil),  // 11: moviepilot.plugin.media.DownloadFileRequest
	(*DownloadFileResponse)(nil), // 12: moviepilot.plugin.media.DownloadFileResponse
	(*HealthCheckRequest)(nil),   // 13: moviepilot.plugin.media.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 14: moviepilot.plugin.media.HealthCheckResponse
}
var file_plugin_media_proto_depIdxs = []int32{
	2,  // 0: moviepilot.plugin.media.SearchResponse.torrents:type_name -> moviepilot.plugin.media.TorrentInfo
	5,  // 1: moviepilot.plugin.media.RecognizeResponse.media:type_name -> moviepilot.plugin.media.MediaInfo
	8,  // 2: moviepilot.plugin.media.ListFilesResponse.files:type_name -> moviepilot.plugin.media.FileInfo
	0,  // 3: moviepilot.plugin.media.PluginMediaService.SearchTorrents:input_type -> moviepilot.plugin.media.SearchRequest
	3,  // 4: moviepilot.plugin.media.PluginMediaService.RecognizeMedia:input_type -> moviepilot.plugin.media.RecognizeRequest
	6,  // 5: moviepilot.plugin.media.PluginMediaService.ListFiles:input_type -> moviepilot.plugin.media.ListFilesRequest
	9,  // 6: moviepilot.plugin.media.PluginMediaService.UploadFile:input_type -> moviepilot.plugin.media.UploadFileRequest
	11, // 7: moviepilot.plugin.media.PluginMediaService.DownloadFile:input_type -> moviepilot.plugin.media.DownloadFileRequest
	13, // 8: moviepilot.plugin.media.PluginMediaService.HealthCheck:input_type -> moviepilot.plugin.media.HealthCheckRequest
	1,  // 9: moviepilot.plugin.media.PluginMediaService.SearchTorrents:output_type -> moviepilot.plugin.media.SearchResponse
	4,  // 10: moviepilot.plugin.media.PluginMediaService.RecognizeMedia:output_type -> moviepilot.plugin.media.RecognizeResponse
	7,  // 11: moviepilot.plugin.media.PluginMediaService.ListFiles:output_type -> moviepilot.plugin.media.ListFilesResponse
	10, // 12: moviepilot.plugin.media.PluginMediaService.UploadFile:output_type -> moviepilot.plugin.media.UploadFileResponse
	12, // 13: moviepilot.plugin.media.PluginMediaService.DownloadFile:output_type -> moviepilot.plugin.media.DownloadFileResponse
	14, // 14: moviepilot.plugin.media.PluginMediaService.HealthCheck:output_type -> moviepilot.plugin.media.HealthCheckResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_media_proto_init() }
func file_plugin_media_proto_init() {
	if File_plugin_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_media_proto_rawDesc), len(file_plugin_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_media_proto_goTypes,
		DependencyIndexes: file_plugin_media_proto_depIdxs,
		MessageInfos:      file_plugin_media_proto_msgTypes,
	}.Build()
	File_plugin_media_proto = out.File
	file_plugin_media_proto_goTypes = nil
	file_plugin_media_proto_depIdxs = nil
}
