// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: plugin_media.proto

package plugin_media

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginMediaService_SearchTorrents_FullMethodName = "/moviepilot.plugin.media.PluginMediaService/SearchTorrents"
	PluginMediaService_RecognizeMedia_FullMethodName = "/moviepilot.plugin.media.PluginMediaService/RecognizeMedia"
	PluginMediaService_ListFiles_FullMethodName      = "/moviepilot.plugin.media.PluginMediaService/ListFiles"
	PluginMediaService_UploadFile_FullMethodName     = "/moviepilot.plugin.media.PluginMediaService/UploadFile"
	PluginMediaService_DownloadFile_FullMethodName   = "/moviepilot.plugin.media.PluginMediaService/DownloadFile"
	PluginMediaService_HealthCheck_FullMethodName    = "/moviepilot.plugin.media.PluginMediaService/HealthCheck"
)

// PluginMediaServiceClient is the client API for PluginMediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 插件媒体服务：站点搜索 / TMDB 识别 / 存储操作
type PluginMediaServiceClient interface {
	// 站点搜索
	SearchTorrents(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// TMDB 识别
	RecognizeMedia(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	// 存储操作
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type pluginMediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginMediaServiceClient(cc grpc.ClientConnInterface) PluginMediaServiceClient {
	return &pluginMediaServiceClient{cc}
}

func (c *pluginMediaServiceClient) SearchTorrents(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, PluginMediaService_SearchTorrents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginMediaServiceClient) RecognizeMedia(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, PluginMediaService_RecognizeMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginMediaServiceClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, PluginMediaService_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginMediaServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, PluginMediaService_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginMediaServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*DownloadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadFileResponse)
	err := c.cc.Invoke(ctx, PluginMediaService_DownloadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginMediaServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PluginMediaService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginMediaServiceServer is the server API for PluginMediaService service.
// All implementations must embed UnimplementedPluginMediaServiceServer
// for forward compatibility.
//
// 插件媒体服务：站点搜索 / TMDB 识别 / 存储操作
type PluginMediaServiceServer interface {
	// 站点搜索
	SearchTorrents(context.Context, *SearchRequest) (*SearchResponse, error)
	// TMDB 识别
	RecognizeMedia(context.Context, *RecognizeRequest) (*RecognizeResponse, error)
	// 存储操作
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPluginMediaServiceServer()
}

// UnimplementedPluginMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginMediaServiceServer struct{}

func (UnimplementedPluginMediaServiceServer) SearchTorrents(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTorrents not implemented")
}
func (UnimplementedPluginMediaServiceServer) RecognizeMedia(context.Context, *RecognizeRequest) (*RecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecognizeMedia not implemented")
}
func (UnimplementedPluginMediaServiceServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedPluginMediaServiceServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedPluginMediaServiceServer) DownloadFile(context.Context, *DownloadFileRequest) (*DownloadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedPluginMediaServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginMediaServiceServer) mustEmbedUnimplementedPluginMediaServiceServer() {}
func (UnimplementedPluginMediaServiceServer) testEmbeddedByValue()                            {}

// UnsafePluginMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginMediaServiceServer will
// result in compilation errors.
type UnsafePluginMediaServiceServer interface {
	mustEmbedUnimplementedPluginMediaServiceServer()
}

func RegisterPluginMediaServiceServer(s grpc.ServiceRegistrar, srv PluginMediaServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginMediaService_ServiceDesc, srv)
}

func _PluginMediaService_SearchTorrents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMediaServiceServer).SearchTorrents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMediaService_SearchTorrents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMediaServiceServer).SearchTorrents(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginMediaService_RecognizeMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMediaServiceServer).RecognizeMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMediaService_RecognizeMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMediaServiceServer).RecognizeMedia(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginMediaService_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMediaServiceServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMediaService_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMediaServiceServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginMediaService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMediaServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMediaService_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMediaServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginMediaService_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMediaServiceServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMediaService_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMediaServiceServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginMediaService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginMediaServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginMediaService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginMediaServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginMediaService_ServiceDesc is the grpc.ServiceDesc for PluginMediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginMediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moviepilot.plugin.media.PluginMediaService",
	HandlerType: (*PluginMediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchTorrents",
			Handler:    _PluginMediaService_SearchTorrents_Handler,
		},
		{
			MethodName: "RecognizeMedia",
			Handler:    _PluginMediaService_RecognizeMedia_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _PluginMediaService_ListFiles_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _PluginMediaService_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _PluginMediaService_DownloadFile_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginMediaService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin_media.proto",
}
